<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/FinalCheck.Comparison/FinalCheck.Comparison.csproj" />
    <ProjectReference Include="../../src/FinalCheck.Data/FinalCheck.Data.csproj" />
    <ProjectReference Include="../../src/FinalCheck.Documents/FinalCheck.Documents.csproj" />
  </ItemGroup>
</Project>
