// <auto-generated />
using System;
using FinalCheck.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalCheck.Data.Migrations
{
    [DbContext(typeof(FinalCheckDbContext))]
    [Migration("20260912234643_AddIndependentComparisonRecords")]
    partial class AddIndependentComparisonRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("FinalCheck:DatabaseSchemaVersion", 4)
                .HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredComparisonRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BaselineSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrentSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaselineSnapshotId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CurrentSnapshotId");

                    b.HasIndex("ResultId");

                    b.ToTable("ComparisonRecords", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredComparisonResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineSnapshotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ComparisonSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentSnapshotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("ComparisonResults", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredDocumentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SnapshotSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DocumentSnapshots", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredFormatRestoreOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContractVersionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractVersionId", "CreatedAtUtc");

                    b.ToTable("FormatRestoreOperations", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredRestoredWorkingCopy", b =>
                {
                    b.Property<Guid>("ContractVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Sha256")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ContractVersionId");

                    b.ToTable("RestoredWorkingCopies", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredComparisonRecord", b =>
                {
                    b.HasOne("FinalCheck.Data.Entities.StoredDocumentSnapshot", null)
                        .WithMany()
                        .HasForeignKey("BaselineSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalCheck.Data.Entities.StoredDocumentSnapshot", null)
                        .WithMany()
                        .HasForeignKey("CurrentSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalCheck.Data.Entities.StoredComparisonResult", null)
                        .WithMany()
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
