// <auto-generated />
using System;
using FinalCheck.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalCheck.Data.Migrations
{
    [DbContext(typeof(FinalCheckDbContext))]
    [Migration("20260910021629_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("FinalCheck:DatabaseSchemaVersion", 1)
                .HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredDocumentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SnapshotSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DocumentSnapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
