// <auto-generated />
using System;
using FinalCheck.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalCheck.Data.Migrations
{
    [DbContext(typeof(FinalCheckDbContext))]
    [Migration("20260913060404_AddContractVersionsAndRounds")]
    partial class AddContractVersionsAndRounds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("FinalCheck:DatabaseSchemaVersion", 7)
                .HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredComparisonRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BaselineSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrentSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaselineSnapshotId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CurrentSnapshotId");

                    b.HasIndex("ResultId");

                    b.ToTable("ComparisonRecords", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredComparisonResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineSnapshotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ComparisonSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentSnapshotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("ComparisonResults", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredContractVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DuplicateReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSourceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParseStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("ProjectId", "Sha256");

                    b.HasIndex("ProjectId", "RoundNumber", "ImportedAtUtc");

                    b.ToTable("ContractVersions", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredDocumentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SnapshotSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DocumentSnapshots", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredFormatRestoreOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContractVersionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractVersionId", "CreatedAtUtc");

                    b.ToTable("FormatRestoreOperations", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredNegotiationRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NegotiationRounds", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BoundTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BoundTemplateVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentBaselineVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastBaselineType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoundTemplateId");

                    b.HasIndex("BoundTemplateVersionId");

                    b.HasIndex("FolderId");

                    b.HasIndex("Status", "UpdatedAtUtc");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredProjectFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProjectFolders", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredRestoredWorkingCopy", b =>
                {
                    b.Property<Guid>("ContractVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Sha256")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ContractVersionId");

                    b.ToTable("RestoredWorkingCopies", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted", "UpdatedAtUtc");

                    b.ToTable("Templates", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParseStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("TemplateId")
                        .IsUnique()
                        .HasFilter("IsCurrent = 1");

                    b.HasIndex("TemplateId", "Version")
                        .IsUnique();

                    b.ToTable("TemplateVersions", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredComparisonRecord", b =>
                {
                    b.HasOne("FinalCheck.Data.Entities.StoredDocumentSnapshot", null)
                        .WithMany()
                        .HasForeignKey("BaselineSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalCheck.Data.Entities.StoredDocumentSnapshot", null)
                        .WithMany()
                        .HasForeignKey("CurrentSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalCheck.Data.Entities.StoredComparisonResult", null)
                        .WithMany()
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredContractVersion", b =>
                {
                    b.HasOne("FinalCheck.Data.Entities.StoredDocumentSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalCheck.Data.Entities.StoredNegotiationRound", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "RoundNumber")
                        .HasPrincipalKey("ProjectId", "Number")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredNegotiationRound", b =>
                {
                    b.HasOne("FinalCheck.Data.Entities.StoredProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredProject", b =>
                {
                    b.HasOne("FinalCheck.Data.Entities.StoredTemplate", null)
                        .WithMany()
                        .HasForeignKey("BoundTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalCheck.Data.Entities.StoredTemplateVersion", null)
                        .WithMany()
                        .HasForeignKey("BoundTemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalCheck.Data.Entities.StoredProjectFolder", null)
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredTemplateVersion", b =>
                {
                    b.HasOne("FinalCheck.Data.Entities.StoredDocumentSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalCheck.Data.Entities.StoredTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
