// <auto-generated />
using System;
using FinalCheck.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalCheck.Data.Migrations
{
    [DbContext(typeof(FinalCheckDbContext))]
    partial class FinalCheckDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("FinalCheck:DatabaseSchemaVersion", 2)
                .HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredComparisonResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineSnapshotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ComparisonSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentSnapshotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("ComparisonResults", (string)null);
                });

            modelBuilder.Entity("FinalCheck.Data.Entities.StoredDocumentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("SnapshotSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DocumentSnapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
